export default async function ServerTime() {
  console.log("✅ Server Component executed on the SERVER");

  const currentTime = new Date().toLocaleTimeString();

  return (
    <div
      style={{
        border: "2px solid green",
        padding: "20px",
        marginBottom: "20px",
      }}
    >
      <h2>Server Component</h2>

      <p>
        Time generated on server:
        <strong> {currentTime}</strong>
      </p>

      <p>
        Refresh the page and you'll get a new time generated by the server.
      </p>
    </div>
  );
}